sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123"
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tLdxgYNp9h63VkpRfpN
    access-key-secret: qWEn764gWMRpB8ehsA681aCQj2zdrl
    bucket-name: wkd-web01
  redis:
    host: localhost
    port: 6379
    password: 123
    database: 10
  wechat:
    appid: wx52295b73eec9f2e1
    secret: ff9d4d92c48b6db80b9592df0e77534a